import Navbar from "@/components/navbar/Navbar"
import { Web3Provider } from "@/components/providers/Web3Provider"
import { NextUIProvider } from "@nextui-org/react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Toaster } from "react-hot-toast"
import "./globals.css"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "TFG Lens Protocol",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
          <Navbar />
          <NextUIProvider>
            <Toaster position="bottom-center" />
            {children}
          </NextUIProvider>
        </Web3Provider>
      </body>
    </html>
  )
}
